# Generated by Django 4.2 on 2023-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0002_platnosczw_sankcje_platnosc_dodane_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platnosc',
            name='zmn',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sankcje',
            name='dodanesank',
            field=models.IntegerField(default=0),
        ),
    ]
