# Generated by Django 4.2 on 2023-04-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0003_platnosc_zmn_alter_sankcje_dodanesank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sankcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sankcjanazwa', models.CharField(max_length=50)),
                ('dodanesank', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sankcja',
                'verbose_name_plural': 'Sankcja',
            },
        ),
    ]
