# Generated by Django 4.2 on 2023-04-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0004_sankcja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sankcje',
        ),
    ]
