# Generated by Django 4.2 on 2023-05-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0006_platnosc_czy_mr_platnosc_wynik_platnosczw_wynikzw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platnosc',
            name='czy_mr',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=3),
        ),
    ]
