# Generated by Django 4.2 on 2023-05-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0007_alter_platnosc_czy_mr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platnosc',
            name='dodane',
            field=models.FloatField(default=0, verbose_name='Deklaracja'),
        ),
        migrations.AlterField(
            model_name='platnosc',
            name='zmn',
            field=models.FloatField(default=0, verbose_name='Zmniejszenie'),
        ),
    ]
