# Generated by Django 4.2 on 2023-05-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0008_alter_platnosc_dodane_alter_platnosc_zmn'),
    ]

    operations = [
        migrations.CreateModel(
            name='MR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_mlody', models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=3)),
            ],
        ),
    ]
