# Generated by Django 4.2 on 2023-05-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0009_mr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mr',
            options={'verbose_name': 'MR', 'verbose_name_plural': 'MR'},
        ),
    ]
