# Generated by Django 4.2 on 2023-05-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0010_alter_mr_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MR',
        ),
    ]
