# Generated by Django 4.2 on 2023-05-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0012_mr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MR',
        ),
    ]
