# Generated by Django 4.2 on 2023-05-11 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kalkulator', '0014_mr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatnoscBydlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanebydlo', models.PositiveIntegerField(default=0)),
                ('zmnbydlo', models.FloatField(default=0)),
                ('wynikbydlo', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscBydlo',
                'verbose_name_plural': 'PlatnoscBydlo',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscChmiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanechmiel', models.FloatField(default=0)),
                ('zmnchmiel', models.FloatField(default=0)),
                ('wynikchmiel', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscChmiel',
                'verbose_name_plural': 'PlatnoscChmiel',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscJPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanejpo', models.FloatField(default=0)),
                ('zmnjpo', models.FloatField(default=0)),
                ('czy_mr', models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=3)),
                ('wynikjpo', models.FloatField(default=0)),
                ('wynikzaz', models.FloatField(default=0)),
                ('wynikredys', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscJPO',
                'verbose_name_plural': 'PlatnoscJPO',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscKonopie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodankonopie', models.FloatField(default=0)),
                ('zmnkonopie', models.FloatField(default=0)),
                ('wynikkonopie', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscKonopie',
                'verbose_name_plural': 'PlatnoscKonopie',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscKozy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanekozy', models.PositiveIntegerField(default=0)),
                ('zmnkozy', models.FloatField(default=0)),
                ('wynikkozy', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscKozy',
                'verbose_name_plural': 'PlatnoscKozy',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscKrowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanekrowy', models.PositiveIntegerField(default=0)),
                ('zmnkrowy', models.FloatField(default=0)),
                ('wynikkrowy', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscKrowy',
                'verbose_name_plural': 'PlatnoscKrowy',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscLen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanelen', models.FloatField(default=0)),
                ('zmnlen', models.FloatField(default=0)),
                ('wyniklen', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscLen',
                'verbose_name_plural': 'PlatnoscLen',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscOwce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodaneowce', models.PositiveIntegerField(default=0)),
                ('zmnowce', models.FloatField(default=0)),
                ('wynikowce', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscOwce',
                'verbose_name_plural': 'PlatnoscOwce',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscP_Burak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanep_burak', models.FloatField(default=0)),
                ('zmnp_burak', models.FloatField(default=0)),
                ('wynikp_burak', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscP_Burak',
                'verbose_name_plural': 'PlatnoscP_Burak',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscP_PAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanep_pas', models.FloatField(default=0)),
                ('zmnp_pas', models.FloatField(default=0)),
                ('wynikp_pas', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscP_PAS',
                'verbose_name_plural': 'PlatnoscP_PAS',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscP_Skrobia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanep_skrobia', models.FloatField(default=0)),
                ('zmnp_skrobia', models.FloatField(default=0)),
                ('wynikp_skrobia', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscP_Skrobia',
                'verbose_name_plural': 'PlatnoscP_Skrobia',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscP_STR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanep_str', models.FloatField(default=0)),
                ('zmnp_str', models.FloatField(default=0)),
                ('wynikp_str', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscP_STR',
                'verbose_name_plural': 'PlatnoscP_STR',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscP_Truskawka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanep_trus', models.FloatField(default=0)),
                ('zmnp_trus', models.FloatField(default=0)),
                ('wynikp_trus', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscP_Truskawka',
                'verbose_name_plural': 'PlatnoscP_Truskawka',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscPomidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanepomidor', models.FloatField(default=0)),
                ('zmnpomidor', models.FloatField(default=0)),
                ('wynikpomidor', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscPomidor',
                'verbose_name_plural': 'PlatnoscPomidor',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscUPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodaneupp', models.FloatField(default=0)),
                ('zmnupp', models.FloatField(default=0)),
                ('wynikupp', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscUPP',
                'verbose_name_plural': 'PlatnoscUPP',
            },
        ),
        migrations.CreateModel(
            name='SankcjaCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanecc', models.IntegerField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SankcjaCC',
                'verbose_name_plural': 'SankcjaCC',
            },
        ),
        migrations.CreateModel(
            name='SankcjaTerminowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodaneterm', models.IntegerField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SankcjaTerminowa',
                'verbose_name_plural': 'SankcjaTerminowa',
            },
        ),
        migrations.DeleteModel(
            name='PlatnoscZW',
        ),
        migrations.RemoveField(
            model_name='platnosc',
            name='czy_mr',
        ),
    ]
