# Generated by Django 4.2 on 2023-05-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0015_platnoscbydlo_platnoscchmiel_platnoscjpo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platnosckonopie',
            old_name='dodankonopie',
            new_name='dodanekonopie',
        ),
    ]
