# Generated by Django 4.2 on 2023-05-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0016_rename_dodankonopie_platnosckonopie_dodanekonopie'),
    ]

    operations = [
        migrations.AddField(
            model_name='platnoscjpo',
            name='wynikmr',
            field=models.FloatField(default=0),
        ),
    ]
