# Generated by Django 4.2.1 on 2023-05-18 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0017_platnoscjpo_wynikmr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MR',
        ),
        migrations.DeleteModel(
            name='Platnosc',
        ),
        migrations.DeleteModel(
            name='Sankcja',
        ),
        migrations.AlterField(
            model_name='platnoscjpo',
            name='dodanejpo',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='platnoscjpo',
            name='zmnjpo',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='platnoscupp',
            name='dodaneupp',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='platnoscupp',
            name='zmnupp',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
