# Generated by Django 4.2.1 on 2023-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0019_alter_platnoscbydlo_zmnbydlo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sankcjaniezadekl',
            name='dodaneniezad',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=1),
        ),
    ]
