# Generated by Django 4.2.1 on 2023-05-24 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kalkulator', '0020_alter_sankcjaniezadekl_dodaneniezad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platnosctyton',
            options={'verbose_name': 'PlatnoscTyton', 'verbose_name_plural': 'PlatnoscTyton'},
        ),
        migrations.RenameField(
            model_name='platnosctyton',
            old_name='dodanevirginia',
            new_name='dodanetyton',
        ),
        migrations.RenameField(
            model_name='platnosctyton',
            old_name='wynikvirginia',
            new_name='wyniktyton',
        ),
        migrations.RenameField(
            model_name='platnosctyton',
            old_name='zmnvirginia',
            new_name='zmntyton',
        ),
        migrations.CreateModel(
            name='PlatnoscVirginia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanevirginia', models.PositiveIntegerField(default=0)),
                ('zmnvirginia', models.PositiveIntegerField(default=0)),
                ('wynikvirginia', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscVirginia',
                'verbose_name_plural': 'PlatnoscVirginia',
            },
        ),
    ]
