# Generated by Django 4.2.1 on 2023-05-25 05:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kalkulator', '0022_remove_platnoscvirginia_uzytkownik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SankcjaNiezadekl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodaneniezad', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=1)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SankcjaNiedeklarowane',
                'verbose_name_plural': 'SankcjaNiedeklarowane',
            },
        ),
        migrations.CreateModel(
            name='SankcjaEFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pow_go', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0, message='Powierzchnia P_Truskawka nie może być wartością ujemną')])),
                ('pow_efa', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0, message='Powierzchnia zmniejszeń nie może być wartością ujemną')])),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SankcjaEFA',
                'verbose_name_plural': 'SankcjaEFA',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscVirginia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanevirginia', models.PositiveIntegerField(default=0)),
                ('zmnvirginia', models.PositiveIntegerField(default=0)),
                ('wynikvirginia', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscVirginia',
                'verbose_name_plural': 'PlatnoscVirginia',
            },
        ),
        migrations.CreateModel(
            name='PlatnoscTyton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dodanetyton', models.PositiveIntegerField(default=0)),
                ('zmntyton', models.PositiveIntegerField(default=0)),
                ('wyniktyton', models.FloatField(default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlatnoscTyton',
                'verbose_name_plural': 'PlatnoscTyton',
            },
        ),
    ]
