# Generated by Django 4.2.1 on 2023-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kalkulator', '0023_sankcjaniezadekl_sankcjaefa_platnoscvirginia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sankcjaefa',
            name='braku_efa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sankcjaefa',
            name='piecproc_efa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sankcjaefa',
            name='proc_efa',
            field=models.FloatField(default=0),
        ),
    ]
